# Generated by Django 4.2.2 on 2024-07-26 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gad_7_number', models.IntegerField(default=0)),
                ('phq_9_number', models.IntegerField(default=0)),
                ('is_gad_7', models.BooleanField(default=False)),
                ('is_phq_9', models.BooleanField(default=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gad_7_count', models.IntegerField(default=0)),
                ('phq_9_count', models.IntegerField(default=0)),
                ('gad_7_completed', models.BooleanField(default=False)),
                ('phq_9_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('emotion', models.JSONField()),
                ('disorder', models.JSONField()),
                ('validation', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gad_7', models.BooleanField(default=False)),
                ('phq_9', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
