# Generated by Django 5.0.6 on 2024-07-08 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chat_disorder_label_chat_disorder_prob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='validation_prob',
        ),
    ]
