# Generated by Django 5.0.6 on 2024-07-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_chat_validation_prob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='disorder_prob',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='chat',
            name='emotion_prob',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='chat',
            name='validation_label',
            field=models.JSONField(),
        ),
    ]
