# Generated by Django 5.0.6 on 2024-07-08 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_chat_disorder_prob_alter_chat_emotion_prob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='disorder_prob',
            new_name='disorder',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='emotion_prob',
            new_name='emotion',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='validation_label',
            new_name='validation',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='disorder_label',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='emotion_label',
        ),
    ]
