# -*- coding: utf-8 -*-
"""pred_emoji.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TPxRjohfVrVFuO7xZOUGVFDN1qzY6Vhl
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
# %matplotlib inline
import re
import pandas as pd
import time
import os
import torch
import random

label_Dict= {
 0:'toxic',0:'severe_toxic',2:'obscene',3:'threat',4:'insult',5:'identity_hate',6:'comment_trans_text',7:'comment_text'
}
def predict(text):
    return label_Dict[random.randint(0, 8)]